kind: pipeline
name: android-build

steps:
  - name: build-app
    image: registry.gandhiva.online/gandhiva-builder:latest
    pull: true 
    commands:
      - cd android
      - bundle exec fastlane android internal
    when:
      - event: [push, manual] # Added manual so you can trigger it from the UI
        branch: [dev, main]   # Matches dev or main
